name: Terraform CI/CD

on:
  push:
    branches:
      - main
  workflow_dispatch: # Cho phép chạy thủ công

env:
  AWS_REGION: ap-southeast-1 # Thay đổi nếu vùng của bạn khác

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.x.x # Bạn có thể chỉ định phiên bản cụ thể nếu muốn

      - name: Terraform Init
        id: init
        run: terraform init -backend-config="region=${{ env.AWS_REGION }}"

      - name: Terraform Validate
        id: validate
        run: terraform validate

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color
        continue-on-error: true # Cho phép job tiếp tục ngay cả khi plan có lỗi (ví dụ: pending changes)

      - name: Terraform Apply
        id: apply
        if: steps.plan.outcome == 'success' || steps.plan.outcome == 'failure' # Chạy apply nếu plan thành công hoặc có lỗi cảnh báo
        run: terraform apply -auto-approve 